name: qr_mobile_vision
description: "Plugin for reading QR codes using Google's Mobile Vision API."
version: 0.1.0
author: Morgan McKenzie <rmtmckenzie@gmail.com>
homepage: https://github.com/rmtmckenzie/flutter_qr_mobile_vision

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

flutter:
  plugin:
    androidPackage: com.github.rmtmckenzie.qrmobilevision
    pluginClass: QrMobileVisionPlugin

dependencies:
  flutter:
    sdk: flutter
  native_device_orientation: ^0.0.2
